# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "alap-virtual-machine"
    vb.memory = "1024"
  end
  config.vm.network "forwarded_port", guest: 80, host: 8080
  # Provision with a shell script
  config.vm.provision "shell", path: "install_apache.sh"
end
