apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-world
  name: hello-world
spec:
  containers:
  - image: hello-world
    name: hello-world
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
